[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "#static"

[build.environment]
  VITE_API_URL = "https://api.cvnova.com/v1"
