[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "#static"

[build.environment]
  NODE_VERSION = "18"  # Specify Node.js version
