[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true  # Ensures all paths are handled by the frontend

[dev]
  framework = "vite"
  command = "vite dev"

[build.environment]
  NODE_VERSION = "18"  # Specify Node.js version

